FROM registry.fedoraproject.org/fedora-toolbox:42

ARG NAME=homebox

LABEL name="$NAME" \
      summary="Fedora toolbox base container" \
      maintainer="morph"

ENV EDITOR=nvim

# Install packages
RUN dnf -y upgrade \
  && dnf -y install \
  golang \
  htop \
  hugo \
  ncdu \
  neovim \
  python3-pip \
  ripgrep \
  tmux \
  unzip \
  && dnf clean all

