FROM localhost/homebox

ARG NAME=cloud-tools

LABEL name="$NAME" \
      summary="Fedora container to run all of the cloud provider nonsense" \
      maintainer="morph"

# install awscli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf ./aws awscliv2.zip

# add kubernetes repo
RUN cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.34/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.34/rpm/repodata/repomd.xml.key
EOF

RUN dnf install -y \
    kubectl \
    helm \
    k9s