FROM homebox:latest

ARG NAME=youtube-dl

LABEL name="$NAME" \
      summary="Youtube downloader toolbox container" \
      maintainer="Marvin"

ENV EDITOR=nvim

# Install packages
RUN dnf -y upgrade \
  && dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  && dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
  && dnf -y install \
  ffmpeg ffmpeg-libs x264 x264-libs \
  && dnf clean all

RUN pip install \
  yt-dlp

COPY bin/* /usr/bin
